run:
  timeout: 3m

linters:
  enable:
    - govet # стандартный анализатор Go
    - staticcheck # статический анализ
    - gosimple # упрощение кода
    - revive # стиль, потенциальные баги
    - errcheck # проверка, что ошибки не игнорируются
    - ineffassign  # неиспользуемые присваивания
    - gofumpt # форматирование (над gofmt)
    - goconst # вынос магических констант
    - gosec #  базовая проверка на безопасность

  disable:
    - depguard
    - funlen
    - unused

